# Generated by Django 2.1 on 2019-03-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190323_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='adress',
            new_name='address',
        ),
    ]
