# Generated by Django 2.1 on 2019-04-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='users_like',
            new_name='user_like',
        ),
    ]
