# Generated by Django 2.1 on 2019-04-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190404_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
