# Generated by Django 2.1 on 2019-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticleTag'),
        ),
    ]
